# This is a config for E2B sandbox template.
# You can use template ID (lxgkikjkm24v96jcskqn) or template name (boilerai-nextjs-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("boilerai-nextjs-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("boilerai-nextjs-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('boilerai-nextjs-dev')

team_id = "781ba57f-1c75-421a-8a3c-62b7ee1d47f0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "boilerai-nextjs-dev"
template_id = "lxgkikjkm24v96jcskqn"
